master:
  image: redis:4.0-alpine
  ports:
    - "6379:6379"
slave:
  image: redis:4.0-alpine
  command: redis-server --slaveof redis-master 6379
  ports:
    - "6380:6379"
  links:
    - master:redis-master
sentinel:
  build: sentinel
  ports:
    - "26379:26379"
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000
  links:
    - master:redis-master
    - slave
